version: '3'
services:
  backend:
    build: .
    volumes:
      - ./public:/usr/src/app/public
  frontend:
    image: nginx:1.13-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/usr/share/nginx/html:ro
    depends_on:
      - backend
    ports:
      - 80:80